# Generated by Django 4.2.7 on 2024-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, default=0, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('insight', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=500)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(blank=True, default=0, null=True)),
                ('impact', models.IntegerField(blank=True, default=0, null=True)),
                ('added', models.CharField(max_length=500)),
                ('published', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('relevance', models.IntegerField(blank=True, default=0, null=True)),
                ('pestle', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1000000)),
                ('likelihood', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
